# Section A: Data Structures & Control Structures

# Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
List1=[7,10,12,18,45]

In [2]:
#Append
List1.append(63)
List1

[7, 10, 12, 18, 45, 63]

In [3]:
#Extend
List1.extend([33,93])
List1

[7, 10, 12, 18, 45, 63, 33, 93]

In [4]:
#Insert
List1.insert(0,4)
List1

[4, 7, 10, 12, 18, 45, 63, 33, 93]

In [5]:
#Remove
List1.remove(45)
List1

[4, 7, 10, 12, 18, 63, 33, 93]

In [6]:
# POP --Removes the element at the mentioned index position
List1.pop(0)
List1

[7, 10, 12, 18, 63, 33, 93]

In [7]:
List1.pop() #removes the last element
List1

[7, 10, 12, 18, 63, 33]

In [8]:
List1.index(10) # gives the index position of 2nd element in list

1

In [9]:
List1.count(12)  # element 3 is present once

1

In [10]:
# sort & reverse
List1.sort(reverse=True)
List1

[63, 33, 18, 12, 10, 7]

In [11]:
#sort
List2=List1
List2.sort()
List2

[7, 10, 12, 18, 33, 63]

In [12]:

#clear
List2.clear()
List2

[]

# Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [13]:
student=('Vishal','Pavan','Shivanand')
student

('Vishal', 'Pavan', 'Shivanand')

In [14]:
student[1]='Shri'

TypeError: 'tuple' object does not support item assignment

Explaination: Tuples are immutable in nature,So we can't change once it's created

# Create a set of integers with some duplicate values. Print the set and explain the output

In [15]:
set = {3,4,3,1,1,3,5,4,6,2,7,8,9}
set

{1, 2, 3, 4, 5, 6, 7, 8, 9}

Explaination: Set is an unordered collecction of elements, if it contains any duplicate means python will remove it by default

# Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [16]:
dict={'name': 'Vishal','age':21,'city':'Mudhol'}
dict

{'name': 'Vishal', 'age': 21, 'city': 'Mudhol'}

In [17]:
dict['age']=22
dict

{'name': 'Vishal', 'age': 22, 'city': 'Mudhol'}

In [18]:
dict['email']='vishalaathresh2003@gmail.com'
dict

{'name': 'Vishal',
 'age': 22,
 'city': 'Mudhol',
 'email': 'vishalaathresh2003@gmail.com'}

# Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [19]:
age=int(input('Enter Your Age'))
if age>=18:
    print('Eligible To Vote')
else:
    print('Not Eligible')

Eligible To Vote


# Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [21]:
Marks=int(input('Enter The Marks'))
if Marks >= 90:
    print("Grade A")
elif Marks >=75:
    print("Grade B")
elif Marks >=50:
    print("Grade C")
else:
    print("fail")

Grade C


# Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [26]:
n=int(input('enter number'))
if n>0:
    if n % 2==0:
        print(n,"is positive and even")
    else:
        print(n, "is positive and odd")
elif n == 0:
    print('number is zero')
else:
    print(n,' is negative')

-4  is negative


# NUMPY

# Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [28]:
import numpy as np
Scalar=np.array(5)
Scalar

array(5)

In [36]:
#1D array
One_dim=np.array([5,4,3,2,1])
One_dim

array([5, 4, 3, 2, 1])

In [39]:
#2D array
Two_dim=np.arange(10,61,10).reshape(2,3)
Two_dim

array([[10, 20, 30],
       [40, 50, 60]])

In [42]:
#2D in manual way
Two_dim1=np.array([[1,2,3],[4,5,6]])
Two_dim1

array([[1, 2, 3],
       [4, 5, 6]])

# Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [43]:
a=np.random.randint(0,100,size=(4,4))
a

array([[46, 93, 83, 68],
       [59,  8, 11, 57],
       [16, 63, 11, 22],
       [54, 86, 92, 28]], dtype=int32)

# Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [44]:
import pandas as pd
two_dim2= np.array([[1,2,3],[4,5,6],[7,8,9]])
two_dim2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
df=pd.DataFrame(two_dim2, columns=['A','B','C'])
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

# PANDAS

# Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [70]:
data = {
    'Name': ['Vishal', 'Shivanand', 'Pavan', 'Prabhu', 'Nikhil', 'Lala', 'Siddu', 'Shiva', 'Dhanush', 'Praful'],
    'Age': [33, 25, 38, 30, 23, 58, 27, 32, 45, 25],
    'City': ['Bengaluru', 'Delhi', 'Bengaluru', 'Chennai', 'Mumbai', 'Vizag', 'Bengaluru', 'Pune', 'Bengaluru', 'Hyderabad'],
    'Salary': [120000, 550000, np.nan, 60000, 80000, np.nan, 85000, 53000, 100000, 50000]
}
df = pd.DataFrame(data)

In [71]:
df

Name  Age       City    Salary
0     Vishal   33  Bengaluru  120000.0
1  Shivanand   25      Delhi  550000.0
2      Pavan   38  Bengaluru       NaN
3     Prabhu   30    Chennai   60000.0
4     Nikhil   23     Mumbai   80000.0
5       Lala   58      Vizag       NaN
6      Siddu   27  Bengaluru   85000.0
7      Shiva   32       Pune   53000.0
8    Dhanush   45  Bengaluru  100000.0
9     Praful   25  Hyderabad   50000.0

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [73]:
df.describe

<bound method NDFrame.describe of         Name  Age       City    Salary
0     Vishal   33  Bengaluru  120000.0
1  Shivanand   25      Delhi  550000.0
2      Pavan   38  Bengaluru       NaN
3     Prabhu   30    Chennai   60000.0
4     Nikhil   23     Mumbai   80000.0
5       Lala   58      Vizag       NaN
6      Siddu   27  Bengaluru   85000.0
7      Shiva   32       Pune   53000.0
8    Dhanush   45  Bengaluru  100000.0
9     Praful   25  Hyderabad   50000.0>

In [74]:
df_name_city = df[['Name', 'City']]
df_name_city

Name       City
0     Vishal  Bengaluru
1  Shivanand      Delhi
2      Pavan  Bengaluru
3     Prabhu    Chennai
4     Nikhil     Mumbai
5       Lala      Vizag
6      Siddu  Bengaluru
7      Shiva       Pune
8    Dhanush  Bengaluru
9     Praful  Hyderabad

In [75]:
df_drop = df.drop('City',axis=1)

In [76]:
df_drop

Name  Age    Salary
0     Vishal   33  120000.0
1  Shivanand   25  550000.0
2      Pavan   38       NaN
3     Prabhu   30   60000.0
4     Nikhil   23   80000.0
5       Lala   58       NaN
6      Siddu   27   85000.0
7      Shiva   32   53000.0
8    Dhanush   45  100000.0
9     Praful   25   50000.0

In [77]:
sal_mean=df['Salary'].mean()

In [78]:
df['Salary'] = df['Salary'].fillna(sal_mean)

In [79]:
df

Name  Age       City    Salary
0     Vishal   33  Bengaluru  120000.0
1  Shivanand   25      Delhi  550000.0
2      Pavan   38  Bengaluru  137250.0
3     Prabhu   30    Chennai   60000.0
4     Nikhil   23     Mumbai   80000.0
5       Lala   58      Vizag  137250.0
6      Siddu   27  Bengaluru   85000.0
7      Shiva   32       Pune   53000.0
8    Dhanush   45  Bengaluru  100000.0
9     Praful   25  Hyderabad   50000.0

In [80]:
duplicate_df = df.drop_duplicates()
duplicate_df 

Name  Age       City    Salary
0     Vishal   33  Bengaluru  120000.0
1  Shivanand   25      Delhi  550000.0
2      Pavan   38  Bengaluru  137250.0
3     Prabhu   30    Chennai   60000.0
4     Nikhil   23     Mumbai   80000.0
5       Lala   58      Vizag  137250.0
6      Siddu   27  Bengaluru   85000.0
7      Shiva   32       Pune   53000.0
8    Dhanush   45  Bengaluru  100000.0
9     Praful   25  Hyderabad   50000.0